# # List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
# tasks:
#   - name: Script Task
#     init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
#     command: echo 'start script'

# # List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
# ports:
#   - name: Frontend
#     description: Port 3000 for the frontend
#     port: 3000
#     onOpen: open-preview

# # Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

image: gitpod/workspace-full

# Commands that will run on workspace start
tasks:
    - name: Setup, Install & Build
      before: yarn global add express
      init: yarn install
      command: yarn build

# Ports to expose on workspace startup
ports:
    - port: 3000
      onOpen: open-preview
      name: Website
      description: Website Preview
      visibility: private
      protocol: https
tasks:
  - command: |
      npm install
      npm start

ports:
  - port: 3000
    onOpen: open-preview