# # List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - command: |
      npm install
      npm start

# # List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - port: 3000
    onOpen: open-preview

# # Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
